---
name: Build and Deploy React App to Github Pages
on:
 push:
  branches: [ main ]
  jobs: 
    build-and-deploy: 
     name: Build and Deploy
     runs-on: ubuntu-latest


     steps:
      - name: Checkout
         uses: action/checkout@v2
     
     - name: Build
        run: npm install

        - name: Test
          run: npm run test

          -name: Deploy
            run: |
               git config --global user.name 'Matheusrrcs'
               git config --global user.email 'matheus-santana-msn@hotmail.com'
               git remote set-url origin https://x-acess-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
               npm run public